### PR TITLE
Fix potential deadlock

### PR DESCRIPTION
**Pull request by tikste**
Hi,

Thanks for your nice little crate.

I changed the following:
* Add support for calling wait before counting down
* Fixed a deadlock that occurs when using async-std
* Bumped versions

You might want to accept my changes.

Regards

### CODE REVIEW

**Comment by tikste** [comment]
I realized, that the deadlock shows up when using a parallel set up. So it's not about async-std, but rather about using ThreadPool vs. LocalPool. Thus, I changed the tests to make use of ThreadPool.

**Comment by wolf4ood** [comment]
Hi @tikste 

thanks for this PR, are the tests running on your local machine?

**Comment by tikste** [comment]
I hope they'll pass now.

**Comment by tikste** [comment]
Hi @wolf4ood 

could you run the tests again, please?

**Comment by wolf4ood** [comment]
@tikste 

sure :)

**Comment by tikste** [comment]
Thanks! Waiting for your review now.

**Review by wolf4ood — APPROVED** [review]
LGTM thanks :)

**Comment by tikste** [comment]
Could you update the version and the crate at crates.io as well, please? Thank you!

**Comment by wolf4ood** [comment]
will do as soon as i can thanks

**Comment by wolf4ood** [comment]
@tikste Just released a 0.3.0 version with this fix

Thanks

**Pull request merged**
